# Generated by Django 2.1.7 on 2019-04-28 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.IntegerField(default=0)),
                ('pmkArtist', models.TextField(max_length=50, primary_key=True, serialize=False)),
                ('fldName', models.TextField(max_length=21)),
                ('fldLocation', models.TextField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Releases',
            fields=[
                ('id', models.IntegerField(default=0)),
                ('pmkRelease', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('fldName', models.TextField(max_length=101)),
                ('fnkArtist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunburst.Artists')),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.IntegerField(default=0)),
                ('pmkSong', models.TextField(max_length=21, primary_key=True, serialize=False)),
                ('fldTerms', models.TextField(max_length=30)),
                ('fldTitle', models.TextField(max_length=100)),
                ('fldYear', models.IntegerField(default=0)),
                ('fnkArtist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunburst.Artists')),
            ],
        ),
        migrations.AddField(
            model_name='releases',
            name='fnkSong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunburst.Songs'),
        ),
    ]
