# Generated by Django 2.1.7 on 2019-04-26 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=None)),
                ('pmkArtist', models.TextField(max_length=50)),
                ('fldName', models.TextField(max_length=20)),
                ('fldLocation', models.TextField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Releases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=None)),
                ('pmkRelease', models.IntegerField(default=None)),
                ('fldName', models.TextField(max_length=100)),
                ('fnkArtist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Artists')),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=None)),
                ('pmkSong', models.TextField(max_length=20)),
                ('fldTerms', models.TextField(max_length=30)),
                ('fldTitle', models.TextField(max_length=100)),
                ('fldYear', models.IntegerField(default=None)),
                ('fnkArtist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Artists')),
            ],
        ),
        migrations.AddField(
            model_name='releases',
            name='fnkSong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Songs'),
        ),
    ]
